name: CI

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    concurrency:
      group: example-group
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        scope: ${{ github.repository_owner }}
        registry-url: "https://npm.pkg.github.com/"
    - run: bun install
    - run: bun tsc
    - run: |
        pipx install conan
        bun src/serve.ts -- --owner ${{ github.repository_owner }} --repo ${GITHUB_REPOSITORY#*/} --folder test&
        sleep 10
        tests/test.sh
      env:
        CONAN_LOGIN_USERNAME_COCOSERVER: ${{ github.repository_owner }}
        CONAN_PASSWORD_COCOSERVER: ${{ secrets.GITHUB_TOKEN }}
        FILEN_EMAIL: ${{ secrets.FILEN_EMAIL }}
        FILEN_PASSWORD: ${{ secrets.FILEN_PASSWORD }}

  publish:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
        scope: ${{ github.repository_owner }}
        registry-url: "https://npm.pkg.github.com/"
    - run: bun publish --access public
      env:
        BUN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
